# Generated by Django 5.0.7 on 2024-07-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="intro",
        ),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.CharField(default="janurary 1,2000", max_length=255),
        ),
    ]
