# Generated by Django 5.0.7 on 2024-07-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_intro_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, default="default.png", upload_to=""),
        ),
    ]
